# Generated by Django 3.0.5 on 2020-12-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_addresssaved_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasetoken',
            name='isSeller',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
