# Generated by Django 3.0.5 on 2020-12-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_firebasetoken_isseller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresssaved',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='firebasetoken',
            old_name='isSeller',
            new_name='is_seller',
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Company'),
        ),
    ]
