# Generated by Django 3.0.5 on 2020-12-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201221_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
